import sys
sys.path.append('..')
from math import *
import numpy as np
from random import *

mu_e  = 7.7425 #T.km^(3)
delta = 9.35*pi/180

def idm(i, u, r): #inclined dipole model
    """
    Get the magnetic field generated by a dipole.
    """
    global delta
    r_ = positionVector(i, u, r)
    k = np.array([[sin(delta)],[0],[cos(delta)]])
    return dipoleField(k, r_, r)

def dipoleField(k, pos, dist):
    """
    Raw formula of a magnetic field created by a dipole.
    """
    global mu_e
    return mu_e/(dist**5)*(dist**2*k-3*np.dot(np.transpose(k),pos)*pos)

def positionVector(i, u, r):
    """
    Calculate the position in the inertial reference frame.
    """
    return r*np.array([[cos(u)],[-sin(u)*cos(i)],[sin(i)*sin(u)]]) #in the inertial frame of reference
